services:
  db:
    image: postgres
    env_file:
      - .env
    restart: always

  backend:
    build: ./backend
    command: npm run dev
    ports:
      - 5000:5000
    volumes:
      - ./backend/src/:/app/src/
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src/:/app/src/
      - ./frontend/public/:/app/public/
    depends_on:
      - backend
    env_file:
      - .env
