import { MapDetail } from "@/components/MapDetail";
import { gql, useQuery } from "@apollo/client";
import Head from "next/head";
import { useRouter } from "next/router";
import { Map } from "../../../../backend/src/entities/Map";

const GET_SCENARIO = gql`
  query Scenario($scenarioId: Int!) {
    scenario(scenarioId: $scenarioId) {
      id
      title
      teaser
      bannerUrl
      fullStory
      maps {
        title
        description
        pictureUrl
        pointsOfInterest {
          code
          title
        }
      }
    }
  }
`;
export default function ScenarioPage() {
  const router = useRouter();

  const { loading, error, data } = useQuery(GET_SCENARIO, {
    variables: { scenarioId: Number(router.query.id) },
  });

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error</p>;
  if (!data) return <p>Not found</p>;

  return (
    <>
      <Head>
        <title>Roleet - Scenario: #1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.scenario.maps.map((map: Map) => (
        <MapDetail {...map} key={map.id} />
      ))}
    </>
  );
}
