import { MapDetail } from "@/components/MapDetail";
import { gql, useQuery } from "@apollo/client";
import Head from "next/head";
import { useRouter } from "next/router";

const GET_FIRST_MAP = gql`
  query Map($mapId: Int!) {
    map(mapId: $mapId) {
      id
      title
      pictureUrl
      description
      pointsOfInterest {
        id
        code
        title
        description
      }
    }
  }
`;
export default function ScenarioPage() {
  const router = useRouter();
  const { loading, error, data } = useQuery(GET_FIRST_MAP, {
    variables: { mapId: Number(router.query.id) },
  });

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error</p>;
  if (!data) return <p>Not found</p>;

  return (
    <>
      <Head>
        <title>Roleet - Scenario: #1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MapDetail {...data.map} />
    </>
  );
}
