import Head from "next/head";
import { useQuery, gql } from "@apollo/client";
// import { CharacterInput } from "../../../backend/src/resolvers/types";
// import { CharacterCard } from "@/components/CharacterCard";
import { ScenarioCard } from "@/components/ScenarioCard";

const GET_CHARACTERS = gql`
  query Characters {
    characters {
      name
      description
      avatarUrl
    }
  }
`;

export default function Home() {
  const { loading, error, data } = useQuery(GET_CHARACTERS);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error</p>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ul className="flex flex-wrap">
        {data.characters.map(
          ({ name, description, avatarUrl }: CharacterInput, i: number) => (
            <CharacterCard key={i} {...{ name, description, avatarUrl }} />
          )
        )}
      </ul> */}
      <ScenarioCard title="Camp Gobelin" />
    </>
  );
}
