import Head from "next/head";
// import { CharacterInput } from "../../../backend/src/resolvers/types";
// import { CharacterCard } from "@/components/CharacterCard";
// import { ScenarioCard } from "@/components/ScenarioCard";
import Link from "next/link";

// const GET_CHARACTERS = gql`
//   query Characters {
//     characters {
//       name
//       description
//       avatarUrl
//     }
//   }
// `;

export default function Home() {
  // const { loading, error, data } = useQuery(GET_CHARACTERS);
  return (
    <>
      <Head>
        <title>Roleet - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        <Link href="/scenarios/1">Détail d&apos;un Scenario</Link>
      </ul>

      {/* <ul className="flex flex-wrap">
        {data.characters.map(
          ({ name, description, avatarUrl }: CharacterInput, i: number) => (
            <CharacterCard key={i} {...{ name, description, avatarUrl }} />
            )
            )}
          </ul> */}
      {/* <ScenarioCard title="Camp Gobelin" /> */}
    </>
  );
}
