import Head from "next/head";
import { useQuery, gql } from "@apollo/client";
import { CharacterInput } from "../../../backend/src/resolvers/types";
import { CharacterCard } from "@/components/CharacterCard";

const GET_CHARACTERS = gql`
  query Characters {
    characters {
      name
      description
    }
  }
`;

export default function Home() {
  const { loading, error, data } = useQuery(GET_CHARACTERS);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error</p>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {data.characters.map(
          ({ name, description }: CharacterInput, i: number) => (
            <CharacterCard key={i} name={name} description={description} />
          )
        )}
      </ul>
    </>
  );
}
